### ISSUE TITLE
Tomcat 8.0.23 install results in 404

### ISSUE THREAD

**Issue by pbromilow** [030/chocolateyautomatic#42]
The install package has been removed from the apache.hippo.nl repo and now is only on the archive repo http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.23/bin/

**Comment by 030** [comment]
https://chocolatey.org/packages/Tomcat/8.0.24

**Comment by 030** [comment]
Please create an issue https://github.com/030/chocolateyautomatic/issues

**Comment by pbromilow** [comment]
Hi,


I can see you have marked this issue closed and have updated the git repo with a new version for tomcat 8.0.26 (which now appears in Chocolatey too).  However, I still need an 8.0.23 Choco install that works, and the scripts still point to the wrong repo.  Are you able to update the choco scripts for the older versions please?


Thanks


________________________________
